web-101/blogger/config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'
  resources :articles do
    resources :comments
  end
  resources :tags
  get '/top', to: "articles#top"
end

web-101/blogger/app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
  
  def tag_list
    self.tags.collect do |tag|
      tag.name
    end.join(", ")
  end
  
  def increment_views
    if self.views == nil
      self.views = 0
    else
      self.views += 1
    end
  end
  
  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end
end

web-101/blogger/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

web-101/blogger/app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :articles, through: :taggings
  
  def to_s
    name
  end
end

web-101/blogger/app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

web-101/blogger/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

web-101/blogger/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    include ArticlesHelper
  
  def index
    @articles = Article.all
    
    respond_to do |format|
      format.html
      format.xml { render :xml => @articles.to_xml }
    end
    
  end
  
  def top
    @articles = Article.order(views: :desc).first(3)
  end
  
  
  def show
    @article = Article.find(params[:id])
    @article.increment_views
    @article.save
    
    @comment = Comment.new
    @comment.article_id = @article.id
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(article_params)
    @article.views = 0
    @article.save
    
    flash.notice = "The Article '#{@article.title}' have been created!"
    
    redirect_to article_path(@article)
  end
  
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    
    flash.notice = "The article have beed destroyed successfully!"
    
    redirect_to articles_path
  end
  
  def edit
    @article = Article.find(params[:id])
  end
  
  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    
    flash.notice = "Article '#{@article.title}' have been updated!"
    
    redirect_to article_path(@article)
  end
  
end

web-101/blogger/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  include CommentsHelper
  
  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]
    
    @comment.save
    
    redirect_to article_path(@comment.article)
  end
  
end

web-101/blogger/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  
  def show
    @tag = Tag.find(params[:id])
  end
  
  def index
    @tags = Tag.all
  end
  
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to tags_path
  end
end

web-101/blogger/app/helpers/application_helper.rb
module ApplicationHelper
end

web-101/blogger/app/helpers/articles_helper.rb
module ArticlesHelper
  
  def article_params
    params.require(:article).permit(:title, :body, :tag_list, :image)
  end
  
end

web-101/blogger/app/helpers/comments_helper.rb
module CommentsHelper
  
  def comment_params
    params.require(:comment).permit(:author_name, :body)
  end
  
end

web-101/blogger/app/helpers/tags_helper.rb
module TagsHelper
end

web-101/blogger/app/views/articles/_comment.html.erb
<div>
  <h4>Comment by <%= comment.author_name %></h4>
  <p class="comment"><%= comment.body %></p>
  <p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later </p>
</div>

web-101/blogger/app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
  <ul>
    <% @article.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title%>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :tag_list %><br />
    <%= f.text_field :tag_list%>
  </p>
  <p>
    <% if @article.image.exists? %>
      <%= image_tag @article.image.url(:thumb) %><br />
    <% end %>
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </P>
  <p>
    <%= f.submit %>
  </p>
<% end %>

web-101/blogger/app/views/articles/_show.html.erb
<ul id="articles">
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article), class: 'article_title' %>
    </li>
  <% end %>
</ul>

<%= link_to "Create New Article", new_article_path, class: "new_article" %>

<br />
<%= link_to "Tag list", tags_path %>

web-101/blogger/app/views/articles/edit.html.erb
<h1>Edit an article</h1>

<%= render partial: 'form' %>

web-101/blogger/app/views/articles/index.html.erb
<h1>All Articles</h1>

<%= render partial: 'show' %>

<link href="http://startup-box-156267.euw1-2.nitrousbox.com" rel="alternate" title="RSS" type="articles/rss+xml" />

web-101/blogger/app/views/articles/new.html.erb
<h1>Create new article</h1>

<%= render partial: 'form' %>

web-101/blogger/app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p>
  Tags:
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>

<p>
  Views:
  <%= @article.views %>
</p>

<p>
  <% if @article.image.exists? %>
    <%= image_tag @article.image.url(:medium) %><br />
  <% end %>
</p>
  
<p><%= @article.body %></p>

<%= link_to "Back to the list", articles_path %>
<%= link_to "Delete Article", article_path(@article),method: :delete, data: {confirm: "Do you want to delete the article ?"} %>
<%= link_to "Edit Article", edit_article_path(@article) %>

<h3>Comments (<%= @article.comments.size %>)</h3>
<%= render partial: 'articles/comment', collection: @article.comments %>
<%= render partial: 'comments/form' %>

web-101/blogger/app/views/articles/top.html.erb
<h1>Top 3 Articles</h1>

<%= render partial: 'show' %>

web-101/blogger/app/views/comments/_form.html.erb
<h3>Post a Comment</h3>

<%= form_for [ @article, @comment ] do |f| %>
  <p>
    <%= f.label :author_name, "Username" %><br/>
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :body %><br/>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

web-101/blogger/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<div id="sidebar">
  Sidebar
  <ul>
    <li><%= link_to "Home", articles_path %></li>
    <li><%= link_to "Tags", tags_path %></li>
    <li><%= link_to "Top 3", top_path %></li>
  </ul>
</div>
  
<p class="flash"><%= flash.notice %></p>
<%= yield %>

</body>
</html>

web-101/blogger/app/views/tags/index.html.erb
<h1>Tags</h1>

<ul>
  <% @tags.each do |tag| %>
    <li>
      <%= link_to tag.name, tag_path(tag) %>,
      <%= link_to "Delete", tag_path(tag), method: :delete, data: {confirm: "Do you want to delete the tag?"} %>
    </li>
  <% end %>
</ul>
<br />
<p>
  <%= link_to "Back to articles list", articles_path %>
</p>

web-101/blogger/app/views/tags/show.html.erb
<h1>Articles tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>

<br />
<%= link_to "Back to tag list", tags_path %>